[package]
name = "fustg_rs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
ctrlc = "3.4"
zmq = { git = "https://github.com/erickt/rust-zmq", branch = "master" }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
